FROM mcr.microsoft.com/playwright:v1.44.1-jammy

# Remove unused files
RUN rm -rf /ms-playwright/firefox-* /ms-playwright/webkit-*

# Define custom function directory
ARG FUNCTION_DIR="/function"

# Install build dependencies
RUN apt-get update && \
    apt-get install -y \
    libtool \
    autoconf \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev \
    xauth \
    xvfb

# Copy function code
RUN mkdir -p ${FUNCTION_DIR}/src

# Copy build files
COPY *.json src ${FUNCTION_DIR}

# Copy src folder
COPY src ${FUNCTION_DIR}/src

# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

# Install Node.js dependencies
RUN npm install

# Install AWS Lambda runtime
RUN npm install aws-lambda-ric

# Build the app
RUN npm run build

# Required for Node runtimes which use npm@8.6.0+ because
# by default npm writes logs under /home/.npm and Lambda fs is read-only
ENV NPM_CONFIG_CACHE=/tmp/.npm

# Required for Playwright because Lambda fs is read-only
ENV HOME=/tmp/

# Playwright debug
ENV DEBUG=pw:browser,pw:api,pw:webserver

# Set runtime interface client as default command for the container runtime
ENTRYPOINT ["xvfb-run", "-a", "npx", "aws-lambda-ric"]

# Pass the name of the function handler as an argument to the runtime
CMD ["dist/app.handler"]
