# Define custom function directory
ARG FUNCTION_DIR="/function"

#FROM node:20-bookworm as build-image
FROM mcr.microsoft.com/playwright:v1.44.1-jammy

# Include global arg in this stage of the build
ARG FUNCTION_DIR

# Install build dependencies
RUN apt-get update && \
    apt-get install -y \
    libtool \
    autoconf \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev \
    xauth \
    xvfb

# Copy function code
RUN mkdir -p ${FUNCTION_DIR}
COPY . ${FUNCTION_DIR}

WORKDIR ${FUNCTION_DIR}

# Install Node.js dependencies
RUN npm install

RUN npm install aws-lambda-ric

RUN npm run build

#RUN npx playwright@1.44.1 install --with-deps chromium

#RUN npx playwright install

# Grab a fresh slim copy of the image to reduce the final size
#FROM node:20-bookworm-slim

# Required for Node runtimes which use npm@8.6.0+ because
# by default npm writes logs under /home/.npm and Lambda fs is read-only
ENV NPM_CONFIG_CACHE=/tmp/.npm

# Include global arg in this stage of the build
#ARG FUNCTION_DIR

# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

# Copy in the built dependencies
#COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}

#RUN npx playwright@1.44.1 install --with-deps chromium

#RUN npx playwright install

# Set runtime interface client as default command for the container runtime
ENTRYPOINT ["xvfb-run", "-a", "npx", "aws-lambda-ric"]

# Pass the name of the function handler as an argument to the runtime
CMD ["dist/app.handler"]
